"""
SAGENT Order PDF Parser

Parses SAGENT orders generated by GaleForceMedia system.

Key Features:
- Multi-market orders (CVC, LAX, SFO, etc.)
- Weekly spot distribution across flight dates
- Rate grossing: Net rates must be divided by 0.85
- Order # goes in Customer Order Ref field
- Estimate # stripped of leading zeros for contract naming

PDF Structure:
- Header: Advertiser, Campaign, Flight Dates, Order #, Estimate #
- Lines: Time Period, Days, Length, Net Rate, Network (Market), Program (Language)
- Weekly columns: Show spot distribution by week
- Bonus lines: $0.00 net rate
"""

import re
from dataclasses import dataclass
from decimal import ROUND_HALF_UP, Decimal
from typing import List, Tuple

import pdfplumber


@dataclass(frozen=True)
class SagentLine:
    """
    A single line item from SAGENT order.
    
    Attributes:
        line_number: Line number from PDF
        time_period: Time range (e.g., "6:00A to 11:59P")
        days: Day pattern (e.g., "M T W R F Sa Su")
        length: Spot duration (e.g., ":15", ":30")
        net_rate: Net rate from PDF (before grossing)
        gross_rate: Grossed rate (net_rate / 0.85)
        market: Market code (e.g., "CVC", "LA", "SFO")
        program: Program/Language (e.g., "CHINESE", "FILIPINO")
        weekly_spots: List of spots per week
        total_spots: Total spots across all weeks
    """
    line_number: int
    time_period: str
    days: str
    length: str
    net_rate: Decimal
    gross_rate: Decimal
    market: str
    program: str
    weekly_spots: List[int]
    total_spots: int

    def is_bonus(self) -> bool:
        """Check if this is a bonus line ($0.00 rate)."""
        return self.net_rate == Decimal("0.00")

    def get_duration_seconds(self) -> int:
        """Convert length to seconds (e.g., ':15' -> 15, ':30' -> 30)."""
        match = re.search(r':(\d+)', self.length)
        if match:
            return int(match.group(1))
        return 15  # Default

    def get_etere_days(self) -> str:
        """Convert day pattern to Etere format via universal day_utils."""
        from browser_automation.day_utils import to_etere
        return to_etere(self.days)

    def get_etere_time(self) -> str:
        """
        Convert time period to Etere format.
        
        Examples:
            "6:00A to 11:59P" -> "6a-11:59p"
            "4:00P to 7:00P" -> "4p-7p"
        """
        # Extract times
        match = re.search(r'(\d+):?(\d+)?([AP]).*?to.*?(\d+):?(\d+)?([AP])', self.time_period, re.IGNORECASE)
        if not match:
            return self.time_period

        start_hour, start_min, start_ampm, end_hour, end_min, end_ampm = match.groups()

        # Format start time (drop :00 minutes)
        start_time = f"{start_hour}"
        if start_min and start_min != "00":
            start_time += f":{start_min}"
        start_time += start_ampm.lower()

        # Format end time (drop :00 minutes)
        end_time = f"{end_hour}"
        if end_min and end_min != "00":
            end_time += f":{end_min}"
        end_time += end_ampm.lower()

        return f"{start_time}-{end_time}"

    def get_language(self) -> str:
        """
        Extract language from program field.
        
        Examples:
            "CHINESE" -> "Chinese"
            "CVC CHINESE" -> "Chinese"
        """
        program_upper = self.program.upper()

        # Map program to language
        if 'CHINESE' in program_upper or 'MANDARIN' in program_upper or 'CANTONESE' in program_upper:
            return "Chinese"
        elif 'FILIPINO' in program_upper or 'TAGALOG' in program_upper:
            return "Filipino"
        elif 'KOREAN' in program_upper:
            return "Korean"
        elif 'VIETNAMESE' in program_upper:
            return "Vietnamese"
        elif 'HMONG' in program_upper:
            return "Hmong"
        elif 'SOUTH ASIAN' in program_upper or 'HINDI' in program_upper or 'PUNJABI' in program_upper:
            return "South Asian"
        elif 'JAPANESE' in program_upper:
            return "Japanese"
        else:
            return "Chinese"  # Default

    def get_description(self) -> str:
        """
        Generate line description for Etere.
        
        SAGENT Format with line numbers:
        - Paid: "(Line #) <Market> <Language>" → "(Line 1) CVC Chinese"
        - Bonus: "(Line #) BNS <Market> <Language>" → "(Line 2) BNS CVC Chinese"
        
        Examples:
            Paid: "(Line 1) CVC Chinese", "(Line 3) LAX Chinese"
            Bonus: "(Line 2) BNS CVC Chinese", "(Line 4) BNS LAX Chinese"
        """
        language = self.get_language()

        if self.is_bonus():
            return f"(Line {self.line_number}) BNS {self.market} {language}"
        else:
            return f"(Line {self.line_number}) {self.market} {language}"


@dataclass(frozen=True)
class SagentOrder:
    """
    Complete SAGENT order.
    
    Attributes:
        advertiser: Client name (e.g., "CAL FIRE")
        campaign: Campaign name (e.g., "2026 CAL FIRE Fourth of July")
        flight_start: Flight start date (MM/DD/YY format)
        flight_end: Flight end date (MM/DD/YY format)
        order_number: Full order number (e.g., "Cros202601282125211")
        estimate_number: Estimate number with leading zeros (e.g., "000202")
        estimate_number_stripped: Estimate without leading zeros (e.g., "202")
        buyer: Buyer name
        brand: Brand name
        week_start_dates: List of week start date strings
        lines: List of SagentLine objects
        markets: List of unique markets in order
    """
    advertiser: str
    campaign: str
    flight_start: str
    flight_end: str
    order_number: str
    estimate_number: str
    estimate_number_stripped: str
    buyer: str
    brand: str
    week_start_dates: List[str]
    lines: List[SagentLine]
    markets: List[str]

    def get_default_contract_code(self) -> str:
        """
        Generate default contract code.
        Format: "Sagent <Client> <Est#>"
        Example: "Sagent Cal Fire 202"
        """
        return f"Sagent {self.advertiser} {self.estimate_number_stripped}"

    def get_default_description(self) -> str:
        """
        Generate default contract description.
        Format: "<Client> <Campaign> Est <Est#>"
        Example: "Cal Fire 2026 CAL FIRE Fourth of July Est 202"
        """
        return f"{self.advertiser} {self.campaign} Est {self.estimate_number_stripped}"

    def get_default_notes(self) -> str:
        """
        Generate default notes.
        Format: "Est <Est#>"
        Example: "Est 202"
        """
        return f"Est {self.estimate_number_stripped}"

    def get_lines_by_market(self, market: str) -> List[SagentLine]:
        """Get all lines for a specific market."""
        return [line for line in self.lines if line.market.upper() == market.upper()]


def gross_up_rate(net_rate: float) -> Decimal:
    """
    Gross up net rate by dividing by 0.85.
    
    Args:
        net_rate: Net rate from PDF
        
    Returns:
        Grossed rate rounded to 2 decimals
        
    Examples:
        >>> gross_up_rate(21.25)
        Decimal('25.00')
        
        >>> gross_up_rate(49.56)
        Decimal('58.31')
    """
    if net_rate == 0:
        return Decimal("0.00")

    net_decimal = Decimal(str(net_rate))
    gross_rate = net_decimal / Decimal("0.85")

    # Round to 2 decimal places
    return gross_rate.quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)


def normalize_market_code(market: str) -> str:
    """
    Normalize market name to standard code.
    
    Args:
        market: Market name from PDF (e.g., "LA", "CVC", "SF")
        
    Returns:
        Standardized market code (e.g., "LAX", "CVC", "SFO")
    """
    market_upper = market.upper().strip()

    mapping = {
        "LA": "LAX",
        "LAX": "LAX",
        "LOS ANGELES": "LAX",
        "SF": "SFO",
        "SFO": "SFO",
        "SAN FRANCISCO": "SFO",
        "CVC": "CVC",
        "CENTRAL VALLEY": "CVC",
        "SACRAMENTO": "CVC",
        "FRESNO": "CVC",
        "SEA": "SEA",
        "SEATTLE": "SEA",
        "NYC": "NYC",
        "NEW YORK": "NYC",
        "HOU": "HOU",
        "HOUSTON": "HOU",
        "CMP": "CMP",
        "CHICAGO": "CMP",
        "MINNEAPOLIS": "CMP",
        "WDC": "WDC",
        "WASHINGTON": "WDC",
        "DC": "WDC",
        "MMT": "MMT",
        "MULTIMARKET": "MMT",
    }

    return mapping.get(market_upper, market_upper)


def _extract_sagent_lines(pdf, n_weeks: int) -> List[SagentLine]:
    """Extract order lines from a GaleForce/SAGENT PDF by WORD COORDINATES.

    The PDF is columnar, but its text-flow extraction interleaves the
    Network(=language) and Program(=market) columns and wraps the language up
    onto the time-period line above the data row. Reading by x-position parses
    each column reliably and — critically — across ALL pages (the old text-line
    parser only read page 1 and mis-assigned market/language/time).

    Column x-bands (PDF points), stable across this GaleForce template even when
    a page is shifted a few px:
        line#  x<90 · len 130–185 · rate 180–220 ·
        language/daypart 220–315 · market 315–405 ·
        weekly spots + total  x>=405  (first n_weeks integers = the weeks)
    Time period is the row directly above (x<135); days are the row below.
    """
    from collections import defaultdict

    _VALID_DAY = {'M', 'T', 'W', 'R', 'F', 'Sa', 'Su'}
    lines: List[SagentLine] = []

    for page in pdf.pages:
        buckets = defaultdict(list)
        for w in page.extract_words(use_text_flow=False):
            buckets[round(w['top'])].append(w)
        rows = [(t, sorted(buckets[t], key=lambda w: w['x0'])) for t in sorted(buckets)]

        for i, (_top, ws) in enumerate(rows):
            if not ws:
                continue
            first = ws[0]
            # A data row starts with the line number (x<90) and has a ':NN' length.
            if not (first['x0'] < 90 and re.fullmatch(r'\d{1,2}', first['text'])):
                continue
            if not any(130 <= w['x0'] < 185 and re.fullmatch(r':\d+', w['text']) for w in ws):
                continue

            line_number = int(first['text'])
            length = next((w['text'] for w in ws
                           if 130 <= w['x0'] < 185 and w['text'].startswith(':')), ':30')
            rate_txt = next((w['text'] for w in ws
                             if 180 <= w['x0'] < 220 and w['text'].startswith('$')), '$0.00')
            net_rate = float(rate_txt.replace('$', '').replace(',', '') or 0)

            above = rows[i - 1][1] if i - 1 >= 0 else []
            below = rows[i + 1][1] if i + 1 < len(rows) else []

            # Market: the code in the Program column (315–405).
            market_raw = next((w['text'] for w in ws
                               if 315 <= w['x0'] < 405 and w['text'].strip().isalpha()), '')
            market = normalize_market_code(market_raw) if market_raw else ''

            # Language/program: tokens in 220–315 on the data row AND on the row
            # above (the language often wraps onto the time-period line).
            program = ' '.join(
                [w['text'] for w in above if 220 <= w['x0'] < 315]
                + [w['text'] for w in ws if 220 <= w['x0'] < 315]
            ).strip()

            # Time period: leading words (x<135) on the row above.
            time_period = ' '.join(w['text'] for w in above if w['x0'] < 135).strip()
            if ' to ' not in time_period:
                time_period = "6:00A to 11:59P"

            # Days: valid day tokens (x<135) on the row below.
            day_toks = [w['text'] for w in below if w['x0'] < 135 and w['text'] in _VALID_DAY]
            days = ' '.join(day_toks) if day_toks else "M T W R F Sa Su"

            # Weekly spots: first n_weeks integers in the spot region (x>=405).
            nums = [int(w['text']) for w in ws
                    if w['x0'] >= 405 and re.fullmatch(r'\d+', w['text'])]
            weekly_spots = nums[:n_weeks] if nums else [0] * n_weeks

            gross_rate = gross_up_rate(net_rate)
            lines.append(SagentLine(
                line_number=line_number,
                time_period=time_period,
                days=days,
                length=length,
                net_rate=Decimal(str(net_rate)),
                gross_rate=gross_rate,
                market=market,
                program=program or "UNKNOWN",
                weekly_spots=weekly_spots,
                total_spots=sum(weekly_spots),
            ))
            print(f"[PARSER] Line {line_number}: {market} {program} - "
                  f"${net_rate} net → ${gross_rate} gross - {sum(weekly_spots)} spots "
                  f"[{time_period}]")

    lines.sort(key=lambda ln: ln.line_number)
    return lines


def parse_sagent_pdf(pdf_path: str) -> SagentOrder:
    """
    Parse SAGENT order PDF.
    
    SAGENT PDFs have a unique multi-line format where each order line
    spans 2-3 text lines:
    Line 1: Line# Length Rate Market Program Week1 Week2 Week3 Total DP GRI NetCost
    Line 2: Time Period
    Line 3: Days
    
    Args:
        pdf_path: Path to PDF file
        
    Returns:
        SagentOrder object with all parsed data
        
    Raises:
        ValueError: If PDF cannot be parsed
    """
    print(f"\n[PARSER] Reading SAGENT PDF: {pdf_path}")

    with pdfplumber.open(pdf_path) as pdf:
        # Read EVERY page — SAGENT/GaleForce orders routinely span multiple pages:
        # line items continue across pages and the final page is a Monthly Totals
        # summary. Reading only page 1 silently dropped every line after the first
        # page. Header fields and the week-column header repeat on each page, so
        # parsing them from the concatenated text still resolves to page 1's copy.
        full_text = "\n".join((p.extract_text() or "") for p in pdf.pages)

        # Parse header information
        advertiser = _extract_field(full_text, r'ADVERTISER:\s*([^\n]+)')
        # Remove "REV: 0" suffix if present
        advertiser = re.sub(r'\s+REV:\s*\d+', '', advertiser).strip()

        campaign = _extract_field(full_text, r'CAMPAIGN:\s*([^\n]+)')
        # Remove "ORDER #:" suffix if present
        campaign = re.sub(r'\s+ORDER #:.*', '', campaign).strip()

        flight_dates = _extract_field(full_text, r'FLIGHT DATES:\s*([^\n]+)')
        # Remove "VENDOR:" suffix if present
        flight_dates = re.sub(r'\s+VENDOR:.*', '', flight_dates).strip()

        order_number = _extract_field(full_text, r'ORDER #:\s*([^\n]+)')
        estimate_number = _extract_field(full_text, r'Estimate #:\s*([^\n]+)')
        buyer = _extract_field(full_text, r'Buyer:\s*([^\n]+)')
        brand = _extract_field(full_text, r'Brand:\s*([^\n]+)')

        # Parse flight dates
        flight_start, flight_end = _parse_flight_dates(flight_dates)

        # Strip leading zeros from estimate
        estimate_stripped = estimate_number.lstrip('0')

        print(f"[PARSER] Advertiser: {advertiser}")
        print(f"[PARSER] Campaign: {campaign}")
        print(f"[PARSER] Flight: {flight_start} - {flight_end}")
        print(f"[PARSER] Order #: {order_number}")
        print(f"[PARSER] Estimate: {estimate_number} (stripped: {estimate_stripped})")

        # Extract week header dates
        # Header looks like: "Jun   Jun   Jun   Tot"
        # But there might be another header line in between
        # So we need to search the next few lines for one containing "Spots"

        week_start_dates = []
        lines_list = full_text.split('\n')

        for idx, line in enumerate(lines_list):
            # Look for the specific week header line
            # Must have: 3+ months AND "Tot" (for Total column)
            months = re.findall(r'\b(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\b', line)

            if len(months) >= 3 and 'Tot' in line:
                print(f"[PARSER] Found month header: {line}")
                print(f"[PARSER] Months found: {months}")

                # Search next few lines for one containing "Spots"
                for offset in range(1, 5):  # Check next 4 lines
                    if idx + offset < len(lines_list):
                        day_line = lines_list[idx + offset]
                        print(f"[PARSER] Checking line +{offset}: {day_line}")

                        # Check if this line has "Spots" to confirm it's the day line
                        if 'Spots' in day_line or 'spots' in day_line.lower():
                            print(f"[PARSER] Found day line with 'Spots': {day_line}")

                            # Extract all numbers from the day line
                            # They should be 1-2 digits
                            day_numbers = re.findall(r'\b(\d{1,2})\b', day_line)
                            print(f"[PARSER] Days found: {day_numbers}")

                            # Match all months with day numbers
                            if len(day_numbers) >= len(months):
                                for month, day in zip(months, day_numbers[:len(months)]):
                                    week_start_dates.append(f"{month} {day}")

                                print(f"[PARSER] Week start dates: {week_start_dates}")
                                break

                if week_start_dates:
                    break

        if not week_start_dates:
            print("[PARSER] WARNING: Could not parse week columns - will use contract dates")

        print(f"[PARSER] Week columns: {week_start_dates}")

        # Parse line items by WORD COORDINATES across ALL pages. The old
        # text-flow parser read only page 1 and mis-assigned market/language/time
        # because this GaleForce layout interleaves the Network(language) and
        # Program(market) columns and wraps the language onto the time line.
        n_weeks = len(week_start_dates) if week_start_dates else 3
        lines = _extract_sagent_lines(pdf, n_weeks)

        if not lines:
            raise ValueError("No lines parsed from PDF")

        # Reconcile against the order's own Monthly Totals — guards against a
        # dropped page or line (the very bug this rewrite fixes: silent partial
        # entry). The summary page prints "Total $59,675.00 945".
        _gt = re.search(r'Total\s+\$([\d,]+\.\d{2})\s+(\d+)\b', full_text)
        if _gt:
            grand_net = float(_gt.group(1).replace(',', ''))
            grand_spots = int(_gt.group(2))
            got_spots = sum(ln.total_spots for ln in lines)
            got_net = sum(float(ln.net_rate) * ln.total_spots for ln in lines)
            if got_spots != grand_spots:
                raise ValueError(
                    f"SAGENT parse incomplete: parsed {got_spots} spots but the order total is "
                    f"{grand_spots} — a page or line was dropped. Refusing to enter a partial order."
                )
            if abs(got_net - grand_net) > 1.0:
                raise ValueError(
                    f"SAGENT net mismatch: parsed ${got_net:,.2f} vs order total ${grand_net:,.2f}."
                )
            print(f"[PARSER] ✓ Reconciled {got_spots} spots / ${got_net:,.2f} net against order total")
        else:
            print("[PARSER] WARNING: no Monthly Totals found — could not reconcile spot count")

        markets = sorted({ln.market for ln in lines if ln.market})

        return SagentOrder(
            advertiser=advertiser,
            campaign=campaign,
            flight_start=flight_start,
            flight_end=flight_end,
            order_number=order_number,
            estimate_number=estimate_number,
            estimate_number_stripped=estimate_stripped,
            buyer=buyer,
            brand=brand,
            week_start_dates=week_start_dates,
            lines=lines,
            markets=markets
        )


def _extract_field(text: str, pattern: str) -> str:
    """Extract field using regex pattern."""
    match = re.search(pattern, text, re.MULTILINE | re.IGNORECASE)
    if match:
        return match.group(1).strip()
    return ""


def _parse_flight_dates(flight_dates: str) -> Tuple[str, str]:
    """
    Parse flight date range.
    
    Args:
        flight_dates: Date range string (e.g., "06/08/26 - 07/04/26")
        
    Returns:
        Tuple of (start_date, end_date) in MM/DD/YYYY format
    """
    # Extract two MM/DD/YY(YY) dates — ignores trailing text like "Phone: 916-359-8316"
    dates = re.findall(r'\d{1,2}/\d{1,2}/\d{2,4}', flight_dates)
    if len(dates) < 2:
        raise ValueError(f"Invalid flight dates format: {flight_dates}")

    start = dates[0]
    end = dates[1]

    # Convert MM/DD/YY to MM/DD/YYYY
    start_formatted = _format_date(start)
    end_formatted = _format_date(end)

    return start_formatted, end_formatted


def _format_date(date_str: str) -> str:
    """
    Convert MM/DD/YY to MM/DD/YYYY.
    
    Args:
        date_str: Date string (e.g., "06/08/26")
        
    Returns:
        Formatted date (e.g., "06/08/2026")
    """
    parts = date_str.split('/')
    if len(parts) != 3:
        return date_str

    month, day, year = parts

    # Convert 2-digit year to 4-digit
    if len(year) == 2:
        year_int = int(year)
        if year_int >= 0 and year_int <= 50:
            year = f"20{year}"
        else:
            year = f"19{year}"

    return f"{month}/{day}/{year}"


def analyze_weekly_distribution(
    weekly_spots: List[int],
    week_start_dates: List[str],
    contract_end_date: str
) -> List[dict]:
    """
    Analyze weekly spot distribution and create date ranges.
    
    UNIVERSAL RULE: Combine consecutive weeks with identical spot counts.
    
    Args:
        weekly_spots: List of spots per week (e.g., [72, 72, 0])
        week_start_dates: List of week start dates (e.g., ["Jun 15", "Jun 22", "Jun 29"])
        contract_end_date: Contract end date (MM/DD/YYYY format)
        
    Returns:
        List of dictionaries with combined date ranges
    """
    ranges = []

    # If we have proper week dates, create ranges with consecutive week combining
    if week_start_dates and len(week_start_dates) >= len(weekly_spots):
        i = 0
        while i < len(weekly_spots):
            spots = weekly_spots[i]

            if spots == 0:
                i += 1
                continue  # Skip weeks with no spots

            # Start a new range
            range_start_idx = i
            range_spots = spots

            # Look ahead to combine consecutive weeks with same spot count
            j = i + 1
            while j < len(weekly_spots) and weekly_spots[j] == range_spots:
                j += 1

            range_end_idx = j - 1  # Last week with same spot count

            # Convert dates
            start_date = _convert_week_date_to_full(
                week_start_dates[range_start_idx],
                contract_end_date
            )

            # End date is either:
            # - Day before next different week starts, or
            # - Contract end date if this is the last range
            if range_end_idx < len(week_start_dates) - 1:
                # There's a next week - end day before it starts
                next_week_date = _convert_week_date_to_full(
                    week_start_dates[range_end_idx + 1],
                    contract_end_date
                )
                end_date = _subtract_one_day(next_week_date)
            else:
                # Last range - use contract end
                end_date = contract_end_date

            num_weeks = range_end_idx - range_start_idx + 1

            ranges.append({
                'start_date': start_date,
                'end_date': end_date,
                'spots_per_week': range_spots,
                'weeks': num_weeks
            })

            # Move to next different week
            i = j
    else:
        # Fallback: combine all weeks into single range
        total_spots = sum(weekly_spots)
        num_active_weeks = sum(1 for spots in weekly_spots if spots > 0)

        if total_spots > 0 and num_active_weeks > 0:
            spots_per_week = total_spots // num_active_weeks

            ranges.append({
                'start_date': contract_end_date,  # Placeholder - automation uses contract dates
                'end_date': contract_end_date,
                'spots_per_week': spots_per_week,
                'weeks': 1
            })

    return ranges


def _convert_week_date_to_full(week_date: str, reference_date: str) -> str:
    """
    Convert week date like 'Jun 15' to full MM/DD/YYYY format.
    
    Args:
        week_date: Week date (e.g., "Jun 15")
        reference_date: Reference date for year (MM/DD/YYYY)
        
    Returns:
        Full date (MM/DD/YYYY)
    """
    # Extract year from reference
    year = reference_date.split('/')[-1]

    # Parse month and day
    month_name, day = week_date.split()

    month_map = {
        'Jan': '01', 'Feb': '02', 'Mar': '03', 'Apr': '04',
        'May': '05', 'Jun': '06', 'Jul': '07', 'Aug': '08',
        'Sep': '09', 'Oct': '10', 'Nov': '11', 'Dec': '12'
    }

    month_num = month_map.get(month_name, '01')

    return f"{month_num}/{day.zfill(2)}/{year}"


def _add_days_to_week_date(week_date: str, days: int) -> str:
    """
    Add days to a week date.
    
    Args:
        week_date: Week date (e.g., "Jun 15")
        days: Number of days to add
        
    Returns:
        New date (MM/DD/YYYY format - approximated)
    """
    # Parse month and day
    month_name, day = week_date.split()
    day_num = int(day)

    # Simple addition (assumes month doesn't overflow)
    new_day = day_num + days

    month_map = {
        'Jan': '01', 'Feb': '02', 'Mar': '03', 'Apr': '04',
        'May': '05', 'Jun': '06', 'Jul': '07', 'Aug': '08',
        'Sep': '09', 'Oct': '10', 'Nov': '11', 'Dec': '12'
    }

    month_num = month_map.get(month_name, '01')

    # Use current year (2026 for SAGENT orders)
    return f"{month_num}/{new_day:02d}/2026"


def _subtract_one_day(date_str: str) -> str:
    """
    Subtract one day from a date.
    
    Args:
        date_str: Date in MM/DD/YYYY format
        
    Returns:
        New date in MM/DD/YYYY format
    """
    from datetime import datetime, timedelta

    # Parse the date
    date_obj = datetime.strptime(date_str, '%m/%d/%Y')

    # Subtract one day
    new_date = date_obj - timedelta(days=1)

    # Format back to MM/DD/YYYY
    return new_date.strftime('%m/%d/%Y')


if __name__ == "__main__":
    import sys

    if len(sys.argv) < 2:
        print("Usage: python sagent_parser.py <pdf_path>")
        sys.exit(1)

    pdf_path = sys.argv[1]

    try:
        order = parse_sagent_pdf(pdf_path)

        print("\n" + "="*70)
        print("SAGENT ORDER SUMMARY")
        print("="*70)
        print(f"Advertiser: {order.advertiser}")
        print(f"Campaign: {order.campaign}")
        print(f"Flight: {order.flight_start} - {order.flight_end}")
        print(f"Order #: {order.order_number}")
        print(f"Estimate: {order.estimate_number} (stripped: {order.estimate_number_stripped})")
        print(f"Markets: {', '.join(order.markets)}")
        print(f"\nDefault Contract Code: {order.get_default_contract_code()}")
        print(f"Default Description: {order.get_default_description()}")
        print(f"Default Notes: {order.get_default_notes()}")
        print(f"\nTotal Lines: {len(order.lines)}")
        print(f"Total Spots: {sum(line.total_spots for line in order.lines)}")

        print("\n" + "="*70)
        print("LINES")
        print("="*70)
        for line in order.lines:
            print(f"\nLine {line.line_number}: {line.market} {line.program}")
            print(f"  Time: {line.time_period}")
            print(f"  Days: {line.days}")
            print(f"  Rate: ${line.net_rate} net → ${line.gross_rate} gross")
            print(f"  Spots: {line.weekly_spots} = {line.total_spots} total")
            print(f"  Description: {line.get_description()}")

    except Exception as e:
        print(f"\n✗ Error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
