"""
Sierra Donor Services Media Plan Parser

Parses "Crossings TV Media Plan" PDFs generated by CTV AEs for Sierra Donor Services.

PDF Layout (text-based — pdfplumber extracts clean text):
  Header block:
    Crossings TV Media Plan  Option 2
    Date: M/D/YYYY  Station: Crossings TV
    Adertiser: <Advertiser>  Acct Rep: <AE Name>
    Client Email: ...  Email: ...
    Market <Market City>

  Airtime table columns:
    Language Block | Day Part/Program | Length | Start Date | End Date |
    Spot Type | Total Spot # | Spot Cost | Total Airtime Cost | Spot Value | Line Total Value

  Data rows:
    Chinese     | M-F (7p-12a), Sat-Sun 8p-12a | 30 seconds | 5/1/2026 | 5/31/2026 | COM | 40 | $36.00 | ...
    Vietnamese  | M-Sun (11a-1p)                | 30 seconds | 5/1/2026 | 5/31/2026 | COM | 32 | $30.00 | ...
    Hmong       | Sa-Su (6p-8p)                 | 30 seconds | 5/1/2026 | 5/31/2026 | COM | 20 | $30.00 | ...
    Chinese/... | ROS BONUS                     | 30 seconds | ...      | ...       | BON | 40 | $0     | ...

Key Business Rules:
  - Lines with comma-separated dayparts (e.g. "M-F (7p-12a), Sat-Sun 8p-12a") produce
    multiple SierraLine entries (one per daypart). Spot split is resolved at input time.
  - is_bonus: spot_type == "BON"
  - Market: "Central Valley" → "CVC"; parsed from header
  - Date format in PDF: M/D/YYYY → normalized to MM/DD/YYYY
  - Rate: "$ 36.00" → 36.0 (strip $ and spaces); "$ -" → 0.0
"""

import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import List, Optional, Tuple

_project_root = Path(__file__).parent.parent.parent
if str(_project_root) not in sys.path:
    sys.path.insert(0, str(_project_root))

import pdfplumber

# ─────────────────────────────────────────────────────────────────────────────
# CONSTANTS
# ─────────────────────────────────────────────────────────────────────────────

_MARKET_MAP = {
    "central valley": "CVC",
    "san francisco":  "SFO",
    "los angeles":    "LAX",
    "seattle":        "SEA",
    "houston":        "HOU",
    "chicago":        "CMP",
    "washington":     "WDC",
    "new york":       "NYC",
}

_DAY_NORMALIZE = {
    "m-su":    "M-Su",
    "m-sun":   "M-Su",
    "m-f":     "M-F",
    "m-sa":    "M-Sa",
    "sa-su":   "Sa-Su",
    "sat-sun": "Sa-Su",
    "sa":      "Sa",
    "su":      "Su",
    "sun":     "Su",
    "sat":     "Sa",
}

# ─────────────────────────────────────────────────────────────────────────────
# DATACLASSES
# ─────────────────────────────────────────────────────────────────────────────

@dataclass(frozen=True)
class SierraLine:
    """A single Etere-ready airtime line from a Sierra Donor media plan."""
    language_block: str    # e.g. "Chinese", "Vietnamese", "Hmong"
    days: str              # normalized: "M-F", "M-Su", "Sa-Su"
    time_str: str          # raw range: "7p-12a", "11a-1p", "6p-8p"
    duration_seconds: int  # always 30 for current template
    start_date: str        # "05/01/2026" (MM/DD/YYYY)
    end_date: str          # "05/31/2026"
    spot_type: str         # "COM" or "BON"
    total_spots: int       # 0 = placeholder for multi-daypart split
    rate: float            # per-spot cost (0.0 for bonus)
    is_bonus: bool


@dataclass
class SierraOrder:
    """Complete parsed Sierra Donor media plan."""
    advertiser: str        # "Sierra Donor Services"
    market: str            # "CVC"
    date: str              # "04/24/2026"
    acct_rep: str          # "Marquice Wong"
    lines: List[SierraLine]


# ─────────────────────────────────────────────────────────────────────────────
# HELPERS
# ─────────────────────────────────────────────────────────────────────────────

def _normalize_market(text: str) -> str:
    text_lower = text.lower().strip()
    for key, code in _MARKET_MAP.items():
        if key in text_lower:
            return code
    return text.strip().upper()[:3]


def _normalize_date(raw: str) -> str:
    """Convert 'M/D/YYYY' → 'MM/DD/YYYY'."""
    raw = raw.strip()
    m = re.match(r'^(\d{1,2})/(\d{1,2})/(\d{4})$', raw)
    if m:
        mo, day, yr = m.groups()
        return f"{int(mo):02d}/{int(day):02d}/{yr}"
    return raw


def _parse_rate(raw: str) -> float:
    """Parse '$ 36.00' or '$ -' → float."""
    raw = raw.strip()
    if re.match(r'^\$?\s*-?\s*$', raw):
        return 0.0
    cleaned = re.sub(r'[\$\s,]', '', raw)
    try:
        return float(cleaned)
    except ValueError:
        return 0.0


def _parse_duration(raw: str) -> int:
    """Parse '30 seconds' → 30."""
    m = re.search(r'(\d+)', raw or "")
    return int(m.group(1)) if m else 30


def _normalize_days(raw: str) -> str:
    """Normalize day abbreviation to canonical Etere form."""
    return _DAY_NORMALIZE.get(raw.strip().lower(), raw.strip())


def _normalize_daypart_text(daypart: str) -> str:
    """
    Normalize raw daypart text from PDF:
    - Join embedded newlines (e.g. "8p-\n12a" → "8p-12a")
    - Collapse spaces around hyphens in day ranges (e.g. "Sat -Sun" → "Sat-Sun")
    """
    daypart = daypart.replace('\n', '')
    # "Sat -Sun" or "M -F" → "Sat-Sun" / "M-F"  (only between word chars)
    daypart = re.sub(r'(\w)\s+-\s*(\w)', r'\1-\2', daypart)
    return daypart.strip()


def _parse_daypart(daypart: str) -> Tuple[str, str]:
    """
    Parse a Day Part/Program field into a single (days, time_str) tuple.

    When multiple comma-separated dayparts appear on one row (e.g.
    "M-F (7p-12a), Sat-Sun 8p-12a"), they are collapsed into a single
    M-Su entry using the first segment's time — matching standard entry
    practice for combined day patterns.

    Handles:
      "M-F (7p-12a), Sat -Sun 8p-\\n12a"  → ("M-Su", "7p-12a")
      "M-Sun (11a-1p)"                     → ("M-Su", "11a-1p")
      "Sa-Su (6p-8p)"                      → ("Sa-Su", "6p-8p")
      "ROS BONUS"                          → ("M-Su", "6a-11:59p")
    """
    daypart = _normalize_daypart_text(daypart)

    if "BONUS" in daypart.upper():
        return ("M-Su", "6a-11:59p")

    parts = [p.strip() for p in daypart.split(',')]
    parsed = []

    for part in parts:
        # Pattern: "M-F (7p-12a)" — time in parens
        m = re.match(r'^([A-Za-z][\w\-]*)\s*\(([^)]+)\)\s*$', part)
        if m:
            parsed.append((_normalize_days(m.group(1)), m.group(2).strip()))
            continue

        # Pattern: "Sat-Sun 8p-12a" — time directly after days (no parens)
        m = re.match(r'^([A-Za-z][\w\-]*)\s+(\S.*)$', part, re.DOTALL)
        if m:
            parsed.append((_normalize_days(m.group(1)), m.group(2).strip()))
            continue

        parsed.append(("M-Su", "6a-11:59p"))

    if not parsed:
        return ("M-Su", "6a-11:59p")

    # Multiple segments → collapse to M-Su using the first segment's time
    if len(parsed) > 1:
        return ("M-Su", parsed[0][1])

    return parsed[0]


def _find_airtime_table(tables: list) -> Optional[list]:
    """Find the table that contains the 'Language Block' header row."""
    for table in tables:
        for row in table:
            if row and any(
                cell and "Language" in str(cell)
                for cell in row if cell
            ):
                return table
    return None


def _col_index(header_row: list, *candidates) -> Optional[int]:
    """Find column index matching any candidate substring (case-insensitive)."""
    for i, cell in enumerate(header_row):
        cell_str = str(cell or "").strip().lower().replace("\n", " ")
        for candidate in candidates:
            if candidate.lower() in cell_str:
                return i
    return None


# ─────────────────────────────────────────────────────────────────────────────
# XLSX PARSER
# ─────────────────────────────────────────────────────────────────────────────

def parse_sierra_xlsx(xlsx_path: str) -> SierraOrder:
    """
    Parse a Crossings TV Media Plan Excel file for Sierra Donor Services.

    The Excel format has the same structure as the PDF but with clean
    datetime objects for dates and numeric values for spots/rates.
    """
    print(f"\n[SIERRA PARSER] Reading Excel: {xlsx_path}")

    import openpyxl
    wb = openpyxl.load_workbook(str(xlsx_path), data_only=True)
    ws = wb.active

    rows = [
        [cell.value for cell in row]
        for row in ws.iter_rows()
    ]

    # ── Header fields ──────────────────────────────────────────────────────
    advertiser = acct_rep = market_raw = date_raw = ""

    for row in rows[:10]:
        row_str = " ".join(str(v or "") for v in row)
        if not advertiser:
            m = re.search(r'[Aa]d[ev]?ertiser[:\s]+(.+?)(?:\s{2,}|Acct Rep|$)', row_str)
            if m:
                advertiser = m.group(1).strip()
        if not acct_rep:
            m = re.search(r'Acct Rep[:\s]+(.+)', row_str)
            if m:
                acct_rep = m.group(1).strip()
        if not market_raw:
            m = re.search(r'Market\s+(\w[\w ]+)', row_str)
            if m:
                market_raw = m.group(1).strip()

        # Date cell may be a datetime object
        for cell_val in row:
            if hasattr(cell_val, 'strftime') and not date_raw:
                date_raw = cell_val.strftime('%m/%d/%Y')

    market = _normalize_market(market_raw) if market_raw else "CVC"

    # Direct cell lookup for advertiser/acct_rep if regex missed
    for row in rows[:10]:
        for i, v in enumerate(row):
            v_str = str(v or "")
            if "Adertiser" in v_str or "Advertiser" in v_str:
                # Value is in the next non-None cell
                for nv in row[i+1:]:
                    if nv:
                        advertiser = str(nv).strip()
                        break
            if "Acct Rep" in v_str:
                for nv in row[i+1:]:
                    if nv:
                        acct_rep = str(nv).strip()
                        break

    print(f"[SIERRA PARSER] Advertiser: {advertiser}")
    print(f"[SIERRA PARSER] Acct Rep:   {acct_rep}")
    print(f"[SIERRA PARSER] Market:     {market}")

    # ── Find header row (contains "Language Block") ─────────────────────────
    header_idx = None
    header_row = None
    for i, row in enumerate(rows):
        if any("Language" in str(v or "") for v in row):
            header_idx = i
            header_row = row
            break

    if header_row is None:
        raise ValueError("[SIERRA PARSER] Could not find Language Block header row in xlsx")

    col_lang    = _col_index(header_row, "language")
    col_daypart = _col_index(header_row, "day part", "daypart", "program")
    col_length  = _col_index(header_row, "length")
    col_start   = _col_index(header_row, "start")
    col_end     = _col_index(header_row, "end")
    col_type    = _col_index(header_row, "spot type", "type")
    col_spots   = _col_index(header_row, "total spot", "spot #")
    col_cost    = _col_index(header_row, "spot cost")

    missing = [name for name, idx in [
        ("Language Block", col_lang), ("Day Part/Program", col_daypart),
        ("Start Date", col_start), ("End Date", col_end),
        ("Spot Type", col_type), ("Total Spot #", col_spots), ("Spot Cost", col_cost),
    ] if idx is None]
    if missing:
        raise ValueError(f"[SIERRA PARSER] Missing xlsx columns: {missing}")

    # ── Parse data rows ────────────────────────────────────────────────────
    sierra_lines: List[SierraLine] = []
    _SKIP = {"subtotal", "airtime summary", "airtime summary:", "none", ""}

    for row in rows[header_idx + 1:]:
        if not row or all(v is None for v in row):
            continue

        lang_raw = str(row[col_lang] or "").strip()
        if not lang_raw or lang_raw.lower() in _SKIP:
            continue

        daypart_raw  = str(row[col_daypart] or "").strip()
        length_raw   = str(row[col_length]  or "30 seconds").strip() if col_length is not None else "30 seconds"
        start_val    = row[col_start]
        end_val      = row[col_end]
        type_raw     = str(row[col_type]    or "COM").strip().upper()
        spots_val    = row[col_spots]
        cost_val     = row[col_cost]

        # Dates: may be datetime objects or strings
        if hasattr(start_val, 'strftime'):
            start = start_val.strftime('%m/%d/%Y')
        else:
            start = _normalize_date(str(start_val or ""))

        if hasattr(end_val, 'strftime'):
            end = end_val.strftime('%m/%d/%Y')
        else:
            end = _normalize_date(str(end_val or ""))

        # Skip summary/formula rows: must have valid MM/DD/YYYY dates
        if not re.match(r'^\d{2}/\d{2}/\d{4}$', start) or not re.match(r'^\d{2}/\d{2}/\d{4}$', end):
            continue

        # Skip rows where language is numeric or a summary label
        if re.match(r'^\d+\.?\d*$', lang_raw) or lang_raw.lower().startswith("total"):
            continue

        duration  = _parse_duration(length_raw)
        spot_type = type_raw
        is_bonus  = spot_type == "BON"

        try:
            total_spots = int(spots_val) if spots_val is not None else 0
        except (ValueError, TypeError):
            total_spots = 0

        try:
            rate = 0.0 if is_bonus else float(cost_val or 0)
        except (ValueError, TypeError):
            rate = 0.0

        days, time_str = _parse_daypart(daypart_raw)
        sierra_lines.append(SierraLine(
            language_block=lang_raw,
            days=days,
            time_str=time_str,
            duration_seconds=duration,
            start_date=start,
            end_date=end,
            spot_type=spot_type,
            total_spots=total_spots,
            rate=rate,
            is_bonus=is_bonus,
        ))

    if not sierra_lines:
        raise ValueError("[SIERRA PARSER] No data lines found in xlsx")

    print(f"[SIERRA PARSER] Parsed {len(sierra_lines)} Etere lines")
    for sl in sierra_lines:
        flag = "BONUS" if sl.is_bonus else f"${sl.rate:.2f}"
        print(f"  {sl.language_block:<30} {sl.days:<8} {sl.time_str:<15} "
              f"{sl.spot_type:<4} {sl.total_spots:>4} spots  {flag}")

    return SierraOrder(
        advertiser=advertiser,
        market=market,
        date=date_raw,
        acct_rep=acct_rep,
        lines=sierra_lines,
    )


# ─────────────────────────────────────────────────────────────────────────────
# MAIN PARSER
# ─────────────────────────────────────────────────────────────────────────────

def parse_sierra_pdf(pdf_path: str) -> SierraOrder:
    """
    Parse a Crossings TV Media Plan PDF for Sierra Donor Services.

    Multi-daypart lines (comma-separated in the Day Part field) produce
    multiple SierraLine entries with total_spots=0 as a placeholder.
    The caller (gather_sierra_inputs) resolves the spot split before automation.

    Raises:
        ValueError: If the airtime table or critical columns cannot be found.
    """
    print(f"\n[SIERRA PARSER] Reading: {pdf_path}")

    with pdfplumber.open(pdf_path) as pdf:
        page = pdf.pages[0]
        full_text = page.extract_text() or ""
        tables = page.extract_tables() or []

    # ── Header fields ──────────────────────────────────────────────────────
    def _field(pattern: str) -> str:
        m = re.search(pattern, full_text)
        return m.group(1).strip() if m else ""

    # Template has the typo "Adertiser" (missing 'd') — handle both spellings
    advertiser = _field(r'[Aa]d[ev]?ertiser[:\s]+(.+?)(?:\s{2,}|Acct Rep|$)')
    acct_rep   = _field(r'Acct Rep[:\s]+(.+)')
    market_raw = _field(r'Market\s+(.+)')
    date_raw   = _field(r'Date[:\s]+([0-9/]+)')

    market = _normalize_market(market_raw) if market_raw else "CVC"
    date   = _normalize_date(date_raw)

    print(f"[SIERRA PARSER] Advertiser: {advertiser}")
    print(f"[SIERRA PARSER] Acct Rep:   {acct_rep}")
    print(f"[SIERRA PARSER] Market:     {market}")
    print(f"[SIERRA PARSER] Date:       {date}")

    # ── Airtime table ──────────────────────────────────────────────────────
    airtime_table = _find_airtime_table(tables)
    if not airtime_table:
        raise ValueError("[SIERRA PARSER] Could not find airtime table in PDF")

    header_row = None
    header_idx = 0
    for i, row in enumerate(airtime_table):
        if row and any(cell and "Language" in str(cell) for cell in row if cell):
            header_row = row
            header_idx = i
            break

    if header_row is None:
        raise ValueError("[SIERRA PARSER] Could not find Language Block header row")

    col_lang    = _col_index(header_row, "language")
    col_daypart = _col_index(header_row, "day part", "daypart", "program")
    col_length  = _col_index(header_row, "length")
    col_start   = _col_index(header_row, "start")
    col_end     = _col_index(header_row, "end")
    col_type    = _col_index(header_row, "spot type", "type")
    col_spots   = _col_index(header_row, "total spot", "spot #")
    col_cost    = _col_index(header_row, "spot cost")

    missing = [name for name, idx in [
        ("Language Block", col_lang),
        ("Day Part/Program", col_daypart),
        ("Start Date", col_start),
        ("End Date", col_end),
        ("Spot Type", col_type),
        ("Total Spot #", col_spots),
        ("Spot Cost", col_cost),
    ] if idx is None]
    if missing:
        raise ValueError(f"[SIERRA PARSER] Missing columns: {missing}")

    # ── Parse data rows ────────────────────────────────────────────────────
    sierra_lines: List[SierraLine] = []

    _SKIP = {"subtotal", "airtime summary", "airtime summary:"}

    for row in airtime_table[header_idx + 1:]:
        if not row:
            continue

        lang_raw = str(row[col_lang] or "").strip()
        if not lang_raw or lang_raw.lower() in _SKIP:
            continue

        daypart_raw = str(row[col_daypart] or "").strip()
        length_raw  = str(row[col_length]  or "30 seconds").strip() if col_length is not None else "30 seconds"
        start_raw   = str(row[col_start]   or "").strip()
        end_raw     = str(row[col_end]     or "").strip()
        type_raw    = str(row[col_type]    or "COM").strip().upper()
        spots_raw   = str(row[col_spots]   or "0").strip()
        cost_raw    = str(row[col_cost]    or "$0").strip()

        # Skip summary rows that leak into the language column
        if lang_raw.lower() in _SKIP:
            continue

        duration  = _parse_duration(length_raw)
        start     = _normalize_date(start_raw)
        end       = _normalize_date(end_raw)
        spot_type = type_raw
        is_bonus  = spot_type == "BON"
        rate      = 0.0 if is_bonus else _parse_rate(cost_raw)

        try:
            total_spots = int(re.sub(r'[^\d]', '', spots_raw))
        except (ValueError, TypeError):
            total_spots = 0

        days, time_str = _parse_daypart(daypart_raw)
        sierra_lines.append(SierraLine(
            language_block=lang_raw,
            days=days,
            time_str=time_str,
            duration_seconds=duration,
            start_date=start,
            end_date=end,
            spot_type=spot_type,
            total_spots=total_spots,
            rate=rate,
            is_bonus=is_bonus,
        ))

    if not sierra_lines:
        raise ValueError("[SIERRA PARSER] No data lines found in airtime table")

    print(f"[SIERRA PARSER] Parsed {len(sierra_lines)} Etere lines")
    for sl in sierra_lines:
        flag = "BONUS" if sl.is_bonus else f"${sl.rate:.2f}"
        placeholder = " [split TBD]" if sl.total_spots == 0 and not sl.is_bonus else ""
        print(f"  {sl.language_block:<30} {sl.days:<8} {sl.time_str:<15} "
              f"{sl.spot_type:<4} {sl.total_spots:>4} spots  {flag}{placeholder}")

    return SierraOrder(
        advertiser=advertiser,
        market=market,
        date=date,
        acct_rep=acct_rep,
        lines=sierra_lines,
    )


def parse_sierra(path: str) -> SierraOrder:
    """Dispatch to PDF or Excel parser based on file extension."""
    if Path(path).suffix.lower() in {".xlsx", ".xlsm"}:
        return parse_sierra_xlsx(path)
    return parse_sierra_pdf(path)


# ─────────────────────────────────────────────────────────────────────────────
# STANDALONE TEST
# ─────────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import sys as _sys
    pdf = _sys.argv[1] if len(_sys.argv) > 1 else "incoming/Updated Sierra Donor Proposal.pdf"
    order = parse_sierra_pdf(pdf)
    print(f"\n{'=' * 70}")
    print(f"Advertiser: {order.advertiser}")
    print(f"Market:     {order.market}")
    print(f"Acct Rep:   {order.acct_rep}")
    total_paid  = sum(ln.total_spots for ln in order.lines if not ln.is_bonus)
    total_bonus = sum(ln.total_spots for ln in order.lines if ln.is_bonus)
    total_cost  = sum(ln.total_spots * ln.rate for ln in order.lines)
    print(f"Paid spots: {total_paid}  Bonus: {total_bonus}  Cost: ${total_cost:,.2f}")
