"""Trim the paid lines of H/L Toyota SFO 4Q26 (3137-3139) to their first/last airable dates.

Entered 9/29 with week-boundary windows (Sa-Su 9/28-10/18, M-F 10/19-11/01 ...). Lee 9/30:
"trim to actual dates". Every placement and every ContrattiImportiGiornalieri row already
sits inside the trimmed window (checked 9/30), so this touches CONTRATTIRIGHE dates and the
header MIN/MAX only. Dry run by default; --apply commits and re-reads from a fresh connection.
"""

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from browser_automation.added_value import air_day_bounds  # noqa: E402
from browser_automation.etere_direct_client import connect  # noqa: E402

CONTRACTS = (3137, 3138, 3139)
_PATTERN = {"MTWRF": "M-F", "SU": "Sa-Su", "MTWRFSU": "M-Su", "TWRF": "T-F"}


def lines(cur):
    cur.execute(
        f"""SELECT cr.ID_CONTRATTITESTATA ct, cr.ID_CONTRATTIRIGHE lid, cr.DESCRIZIONE d, cr.DATA_INIZIO ds, cr.DATA_FINE de,
               cr.LUNEDI, cr.MARTEDI, cr.MERCOLEDI, cr.GIOVEDI, cr.VENERDI, cr.SABATO, cr.DOMENICA,
               (SELECT MIN(tp.DATA) FROM trafficPalinse tpa JOIN TPALINSE tp ON tp.ID_TPALINSE=tpa.id_tpalinse WHERE tpa.id_contrattirighe=cr.ID_CONTRATTIRIGHE) p0,
               (SELECT MAX(tp.DATA) FROM trafficPalinse tpa JOIN TPALINSE tp ON tp.ID_TPALINSE=tpa.id_tpalinse WHERE tpa.id_contrattirighe=cr.ID_CONTRATTIRIGHE) p1,
               (SELECT MIN(g.DATA) FROM ContrattiImportiGiornalieri g WHERE g.ID_ContrattiRighe=cr.ID_CONTRATTIRIGHE) g0,
               (SELECT MAX(g.DATA) FROM ContrattiImportiGiornalieri g WHERE g.ID_ContrattiRighe=cr.ID_CONTRATTIRIGHE) g1
            FROM CONTRATTIRIGHE cr WHERE cr.ID_CONTRATTITESTATA IN ({",".join(map(str, CONTRACTS))}) ORDER BY 1, 2"""
    )
    return cur.fetchall()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--apply", action="store_true")
    args = ap.parse_args()
    stamp = (
        Path(__file__).resolve().parents[1]
        / "logs"
        / "hl-toyota-sfo-line-dates-restore-20260930.sql"
    )
    restore = [
        "-- restores the pre-trim line/header dates; generated by trim_hl_toyota_sfo_line_dates.py"
    ]

    with connect() as conn:
        cur = conn.cursor(as_dict=True)
        ok = True
        changed = 0
        for r in lines(cur):
            flags = "".join(
                k
                for k, v in zip(
                    "MTWRFSU",
                    (
                        r["LUNEDI"],
                        r["MARTEDI"],
                        r["MERCOLEDI"],
                        r["GIOVEDI"],
                        r["VENERDI"],
                        r["SABATO"],
                        r["DOMENICA"],
                    ),
                )
                if v
            )
            pat = _PATTERN.get(flags)
            if not pat:
                print(f"{r['ct']} {r['lid']}: unknown day flags {flags} — refusing")
                ok = False
                continue
            ds, de = r["ds"].date(), r["de"].date()
            b = air_day_bounds(ds, de, pat)
            if not b:
                print(f"{r['ct']} {r['lid']}: no airable day — refusing")
                ok = False
                continue
            nf, nt = b
            for lo, hi, what in (
                (r["p0"], r["p1"], "placements"),
                (r["g0"], r["g1"], "revenue rows"),
            ):
                if lo is not None and not (nf <= lo.date() and hi.date() <= nt):
                    print(
                        f"{r['ct']} {r['lid']}: {what} {lo:%m/%d}-{hi:%m/%d} outside {nf}-{nt} — refusing"
                    )
                    ok = False
            if (nf, nt) == (ds, de):
                print(f"{r['ct']} {r['lid']} {pat:5} {ds:%m/%d}-{de:%m/%d} unchanged  {r['d']}")
                continue
            print(
                f"{r['ct']} {r['lid']} {pat:5} {ds:%m/%d}-{de:%m/%d} -> {nf:%m/%d}-{nt:%m/%d}  {r['d']}"
            )
            restore.append(
                f"UPDATE CONTRATTIRIGHE SET DATA_INIZIO='{ds}', DATA_FINE='{de}' WHERE ID_CONTRATTIRIGHE={r['lid']};"
            )
            cur.execute(
                "UPDATE CONTRATTIRIGHE SET DATA_INIZIO=%s, DATESTART=%s, DATA_FINE=%s, DATEEND=%s"
                " WHERE ID_CONTRATTIRIGHE=%s",  # both pairs: the form shows DATESTART/DATEEND
                (nf, nf, nt, nt, r["lid"]),
            )
            assert cur.rowcount == 1
            changed += 1
        for cid in CONTRACTS:
            cur.execute(
                "SELECT DATA_INIZIO ds, DATA_TERMINE de FROM CONTRATTITESTATA WHERE ID_CONTRATTITESTATA=%s",
                (cid,),
            )
            h = cur.fetchone()
            cur.execute(
                "SELECT MIN(DATA_INIZIO) mn, MAX(DATA_FINE) mx FROM CONTRATTIRIGHE WHERE ID_CONTRATTITESTATA=%s",
                (cid,),
            )
            mm = cur.fetchone()
            if (h["ds"], h["de"]) != (mm["mn"], mm["mx"]):
                print(
                    f"header {cid}: {h['ds']:%m/%d}-{h['de']:%m/%d} -> {mm['mn']:%m/%d}-{mm['mx']:%m/%d}"
                )
                restore.append(
                    f"UPDATE CONTRATTITESTATA SET DATA_INIZIO='{h['ds'].date()}', DATA_TERMINE='{h['de'].date()}' WHERE ID_CONTRATTITESTATA={cid};"
                )
                cur.execute(
                    "UPDATE CONTRATTITESTATA SET DATA_INIZIO=%s, DATA_TERMINE=%s WHERE ID_CONTRATTITESTATA=%s",
                    (mm["mn"], mm["mx"], cid),
                )
        print(f"{changed} line(s) trimmed")
        if not (ok and args.apply):
            conn.rollback()
            print(
                "ROLLED BACK"
                + ("" if ok else " (checks failed)")
                + ("" if args.apply else " (dry run; pass --apply)")
            )
            return 0 if ok else 1
        stamp.write_text("\n".join(restore) + "\n")
        conn.commit()
        print("COMMITTED; restore:", stamp)

    with connect() as c2:
        cur = c2.cursor(as_dict=True)
        left = [
            r
            for r in lines(cur)
            if air_day_bounds(
                r["ds"].date(),
                r["de"].date(),
                _PATTERN[
                    "".join(
                        k
                        for k, v in zip(
                            "MTWRFSU",
                            (
                                r["LUNEDI"],
                                r["MARTEDI"],
                                r["MERCOLEDI"],
                                r["GIOVEDI"],
                                r["VENERDI"],
                                r["SABATO"],
                                r["DOMENICA"],
                            ),
                        )
                        if v
                    )
                ],
            )
            != (r["ds"].date(), r["de"].date())
        ]
        cur.execute(
            f"SELECT ID_CONTRATTITESTATA id, CONVERT(VARCHAR(10),DATA_INIZIO,120) ds, CONVERT(VARCHAR(10),DATA_TERMINE,120) de FROM CONTRATTITESTATA WHERE ID_CONTRATTITESTATA IN ({','.join(map(str, CONTRACTS))})"
        )
        print(
            "fresh: untrimmed lines left =",
            len(left),
            "; headers:",
            [(h["id"], h["ds"], h["de"]) for h in cur.fetchall()],
        )
        return 1 if left else 0


if __name__ == "__main__":
    sys.exit(main())
